import {
    AlarmClock,
    AlignJustify,
    Armchair,
    BadgeHelp,
    ChartLine,
    ChevronsUpDown,
    CirclePlus,
    CircleUser,
    Clapperboard,
    Cog,
    Copy,
    FilePenLine,
    Film,
    Inbox,
    LogOut,
    LucideAngularModule,
    PlusCircle,
    Server,
    Settings,
    Store,
    Trash,
    TriangleAlert,
    X,
} from 'lucide-angular';
import { importProvidersFrom } from '@angular/core';

export const lucideIconsProviders = importProvidersFrom(
    LucideAngularModule.pick({
        AlignJustify,
        CircleUser,
        Cog,
        LogOut,
        Inbox,
        BadgeHelp,
        CirclePlus,
        Store,
        ChevronsUpDown,
        Trash,
        Server,
        Copy,
        TriangleAlert,
        ChartLine,
        Clapperboard,
        Film,
        AlarmClock,
        Armchair,
        Settings,
        X,
        PlusCircle,
        FilePenLine,
    })
);
